# Generated by Django 4.2.6 on 2023-11-12 20:41

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('image', models.ImageField(null=True, upload_to='img/')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=255)),
                ('prenom_client', models.CharField(max_length=255)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('adresse', models.CharField(max_length=255)),
                ('courriel', models.CharField(max_length=255)),
                ('num_telephone', models.CharField(max_length=255, null=True)),
                ('date_inscription', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_produit', models.CharField(max_length=255)),
                ('quantite_stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'La quantite doit etre superrieur a 0')])),
                ('description_produit', models.CharField(max_length=255, null=True)),
                ('poids', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0, 'Le poid doit etre superrieur a 0')])),
                ('prixBase', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0, 'Le prix doit etre superrieur a 0')])),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Boutique.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_rabais', models.CharField(choices=[('%', 'Pourcentage'), ('$', 'Unitaire')], max_length=255)),
                ('valeur', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'La valeur doit etre superieur a 0')])),
                ('description_promotion', models.CharField(max_length=255, null=True)),
                ('date_debut', models.DateField(default=datetime.date.today)),
                ('date_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ProduitImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(null=True, upload_to='img/')),
                ('ordre', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'Le prix doit etre superrieur a 0')])),
                ('le_produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Boutique.produit')),
            ],
        ),
        migrations.AddField(
            model_name='produit',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Boutique.promotion'),
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commander', models.BooleanField(default=False)),
                ('date_commander', models.DateTimeField(null=True)),
                ('client', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='CommandeClient', to='Boutique.client', validators=[django.core.validators.MinValueValidator(0, "L'id doit etre superrieur a 0")])),
                ('produit', models.ManyToManyField(to='Boutique.produit')),
            ],
        ),
    ]
