# Generated by Django 4.2.6 on 2023-10-26 20:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('image', models.ImageField(null=True, upload_to='img/')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=255)),
                ('prenom_client', models.CharField(max_length=255)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('adresse', models.CharField(max_length=255)),
                ('courriel', models.CharField(max_length=255)),
                ('num_telephone', models.CharField(max_length=255, null=True)),
                ('date_inscription', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commander', models.BooleanField(default=False)),
                ('date_commander', models.DateTimeField(null=True)),
                ('id_client', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, "L'id doit etre superrieur a 0")])),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_produit', models.CharField(max_length=255)),
                ('quantite_stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'La quantite doit etre superrieur a 0')])),
                ('description_produit', models.CharField(max_length=255, null=True)),
                ('poids', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0, 'Le poid doit etre superrieur a 0')])),
                ('prix', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0, 'Le prix doit etre superrieur a 0')])),
                ('image', models.ImageField(null=True, upload_to='img/')),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Boutique.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='ProduitImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_produit', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, "L'id doit etre superieur a 0")])),
                ('image', models.ImageField(upload_to='img/')),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_rabais', models.CharField(max_length=255)),
                ('valeur', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'La valeur doit etre superieur a 0')])),
                ('description_promotion', models.CharField(max_length=255, null=True)),
                ('produit_touche', models.ManyToManyField(to='Boutique.produit')),
            ],
        ),
    ]
