# Generated by Django 4.2.6 on 2023-12-11 19:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boutique', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandeproduit',
            name='prix_unitaire',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, 'le prix doit etre plus grand que 0')]),
        ),
    ]
