# Generated by Django 4.2.6 on 2023-11-30 19:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Boutique', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='produit',
        ),
        migrations.CreateModel(
            name='CommandeProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, "L'id doit etre superrieur a 0")])),
                ('la_commande', models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='commande_quantite', to='Boutique.commande', validators=[django.core.validators.MinValueValidator(0, "L'id doit etre superrieur a 0")])),
                ('produit_du_panier', models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='Boutique.produit', validators=[django.core.validators.MinValueValidator(0, "L'id doit etre superrieur a 0")])),
            ],
        ),
    ]
