# Generated by Django 4.2.6 on 2023-10-31 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boutique', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='produit',
            field=models.ManyToManyField(to='Boutique.produit'),
        ),
    ]
