# Generated by Django 4.2.6 on 2023-10-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boutique', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('Description', models.CharField(max_length=255)),
                ('prix', models.BigIntegerField()),
                ('img', models.CharField(max_length=255)),
            ],
        ),
    ]
