# Generated by Django 4.2.6 on 2023-10-26 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Boutique', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produitimg',
            old_name='path',
            new_name='image',
        ),
    ]
