# Generated by Django 4.2.6 on 2023-11-07 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Boutique', '0002_commande_produit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProduitImg',
        ),
    ]
