# Generated by Django 4.2.6 on 2023-11-28 16:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Boutique', '0002_remove_client_adresse_remove_client_num_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='CommandeClient', to=settings.AUTH_USER_MODEL, validators=[django.core.validators.MinValueValidator(0, "L'id doit etre superrieur a 0")]),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
