# Generated by Django 4.2.6 on 2023-10-26 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boutique', '0002_rename_path_produitimg_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='img',
        ),
        migrations.AddField(
            model_name='categorie',
            name='image',
            field=models.ImageField(null=True, upload_to='img/'),
        ),
        migrations.AddField(
            model_name='produit',
            name='image',
            field=models.ImageField(null=True, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='produitimg',
            name='image',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
