# Generated by Django 4.2.6 on 2023-11-28 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Boutique', '0002_alter_produit_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produits', to='Boutique.categorie'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='Boutique.promotion'),
        ),
    ]
