# Generated by Django 4.2.6 on 2023-11-07 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Boutique', '0003_delete_produitimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='produit_touche',
        ),
        migrations.AddField(
            model_name='produit',
            name='promotion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Boutique.promotion'),
        ),
    ]
