# Generated by Django 4.2.6 on 2023-10-24 15:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boutique', '0003_client_commande_produitimg_promotion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduitCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_commande', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, "L'id de la promotion doit etre superrieur a 0")])),
                ('id_produit', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, "L'id du produit doit etre superrieur a 0")])),
            ],
        ),
        migrations.CreateModel(
            name='PromotionProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_promotion', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, "L'id de la promotion doit etre superrieur a 0")])),
                ('id_produit', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, "L'id du produit doit etre superrieur a 0")])),
            ],
        ),
        migrations.RenameField(
            model_name='commande',
            old_name='dateCommander',
            new_name='date_commander',
        ),
        migrations.AddField(
            model_name='produit',
            name='poid',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0, 'Le poid doit etre superrieur a 0')]),
        ),
    ]
