# Generated by Django 4.2.6 on 2023-11-12 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boutique', '0004_alter_promotion_date_debut_alter_promotion_date_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='promo_valide',
            field=models.BooleanField(null=True),
        ),
    ]
