# Generated by Django 4.2.6 on 2023-10-24 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Boutique', '0004_produitcommande_promotionproduit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='poid',
            new_name='poids',
        ),
    ]
