# Generated by Django 4.2.6 on 2023-11-07 15:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boutique', '0004_remove_promotion_produit_touche_produit_promotion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='prix',
            new_name='prixBase',
        ),
        migrations.AddField(
            model_name='produit',
            name='prixFinal',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0, 'Le prix doit etre superrieur a 0')]),
        ),
    ]
