# Generated by Django 4.2.6 on 2023-10-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boutique', '0005_rename_poid_produit_poids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='id_categorie',
        ),
        migrations.AddField(
            model_name='produit',
            name='id_categorie',
            field=models.ManyToManyField(to='Boutique.categorie'),
        ),
    ]
