# Generated by Django 4.2.6 on 2023-11-07 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Boutique', '0005_rename_prix_produit_prixbase_produit_prixfinal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='prixFinal',
        ),
        migrations.AlterField(
            model_name='produit',
            name='promotion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Boutique.promotion'),
        ),
    ]
