# Generated by Django 4.2.6 on 2023-11-07 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Boutique', '0006_remove_produit_prixfinal_alter_produit_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Boutique.categorie'),
        ),
    ]
