# Generated by Django 4.2.6 on 2023-10-24 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Boutique', '0006_remove_produit_id_categorie_produit_id_categorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='id_categorie',
        ),
        migrations.AddField(
            model_name='produit',
            name='id_categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Boutique.categorie'),
        ),
    ]
