# Generated by Django 4.2.6 on 2023-10-24 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Boutique', '0007_remove_produit_id_categorie_produit_id_categorie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='id_categorie',
            new_name='categorie',
        ),
    ]
