# Generated by Django 4.2.6 on 2023-10-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boutique', '0008_rename_id_categorie_produit_categorie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProduitCommande',
        ),
        migrations.DeleteModel(
            name='PromotionProduit',
        ),
        migrations.AddField(
            model_name='promotion',
            name='produit_touche',
            field=models.ManyToManyField(to='Boutique.produit'),
        ),
    ]
