# Generated by Django 4.2.6 on 2023-11-07 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Boutique', '0008_alter_produit_categorie_alter_promotion_type_rabais_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produitimage',
            old_name='idProduit',
            new_name='le_produit',
        ),
    ]
