# Generated by Django 4.2.6 on 2023-11-09 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Boutique', '0009_rename_idproduit_produitimage_le_produit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='image',
        ),
        migrations.AddField(
            model_name='produitimage',
            name='ordre',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='produitimage',
            name='le_produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Boutique.produit'),
        ),
    ]
