# Generated by Django 4.2.6 on 2023-11-09 20:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Boutique', '0010_remove_produit_image_produitimage_ordre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='id_client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Boutique.client', validators=[django.core.validators.MinValueValidator(0, "L'id doit etre superrieur a 0")]),
        ),
    ]
