# Generated by Django 4.2.6 on 2023-11-09 21:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Boutique', '0012_rename_id_client_commande_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='CommandeClient', to='Boutique.client', validators=[django.core.validators.MinValueValidator(0, "L'id doit etre superrieur a 0")]),
        ),
        migrations.AlterField(
            model_name='produit',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Boutique.promotion'),
        ),
        migrations.AlterField(
            model_name='produitimage',
            name='ordre',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'Le prix doit etre superrieur a 0')]),
        ),
    ]
